### ISSUE TITLE
Problems building 

### ISSUE THREAD

**Issue by ghost** [Dappub/fairdicegame#15]
I am trying to compile  locally. But I had the following errors:
When I did `cmake .` inside fairdicegame directory:`CMake Error at CMakeLists.txt:22 (include): include could not find load file: EosioWasmToolChain`
Inside: fairdicegame/fairdicelogs: CMake without error; `make` encountered a fatal error : #include <eosiolib/asset.hpp> eosiolib/asset.hpp: No such file or directory
Inside fairdicegame/fairdicegame: I moved all header files and cpp files under one directory. Then I did `eosio-cpp -o fairdicegame.wasm fairdicegame.cpp --abigen`. It compiled successfully. But the fairdicegame.abi only contains the dafault abi content.

**Comment by onigirisan** [comment]
Please install [eosio.cdt](https://github.com/EOSIO/eosio.cdt) and then rebuild

**Comment by ddoddoddo** [comment]
I had the latest version of eosio.cdt installed. (latest commit 112df8d).

**Comment by onigirisan** [comment]
The version of eosio.cdt used  is v1.1.1, please try again.
I will upgrade it to the latest version later.
