### ISSUE TITLE
Got error 3070000 when set contract on kylin testnet

### ISSUE THREAD

**Issue by wingon-niu** [Dappub/fairdicegame#19]
i moved all .hpp file and .cpp file of fairdicegame into one directory and successfully compiled and gen abi file.

when i set fairdicegame contract on kylin testnet, i got error:

root@03984080db4f:/work/fairdicegame/fairdicegame# cleos set contract niueeeeeeeee ../fairdicegame -p niueeeeeeeee@active
Reading WASM from ../fairdicegame/fairdicegame.wasm...
Publishing contract...
Error 3070000: WASM Exception
Error Details:
env.calloc unresolveable
pending console output: 
root@03984080db4f:/work/fairdicegame/fairdicegame# 

when i set fairdicegame contract on my local testnet ( docker image eos-dev v1.2.6 ),  i got same error, and nodeos console print:

2018-10-06T17:00:41.113 thread-0   http_plugin.cpp:473           handle_exception     ] FC Exception encountered while processing chain.push_transaction
2018-10-06T17:00:41.113 thread-0   http_plugin.cpp:474           handle_exception     ] Exception Details: 3070000 wasm_exception: WASM Exception
env.calloc unresolveable
    {"module":"env","export":"calloc"}
    thread-0  wasm_interface.hpp:42 resolve

    {"mod_name":"env","export_name":"calloc"}
    thread-0  wasm_interface.hpp:44 resolve
pending console output: 
    {"console":""}
    thread-0  apply_context.cpp:61 exec_one

thx

**Comment by wingon-niu** [comment]
Have you ever encountered this problem?

**Comment by jambeau** [comment]
I also encountered this problem and looked forward to solving it.

**Comment by apathymagic** [comment]
https://github.com/Dappub/fairdicegame/blob/44858199981250b6e37d7717fe6e08a2ec7780b0/fairdicegame/include/types.hpp#L7
You can change the code of "static string PUB_KEY" to "#define PUB_KEY" to fix this issue.
`#define PUB_KEY "EOS4wpa8kRBbZof9JEpPAAgbnN65NhbBobW4x5gyxQoFfamhQCAMX"`

**Comment by wingon-niu** [comment]
i also fixed this issue by:
static const char* PUB_KEY = "EOS4wpa8kRBbZof9JEpPAAgbnN65NhbBobW4x5gyxQoFfamhQCAMX";
