### ISSUE TITLE
fairdicegame里对用户传进来的数据为啥要进行签名校验呢？而且是要用指定的私钥签名。

### ISSUE THREAD

**Issue by littlekfc** [Dappub/fairdicegame#2]
只是单纯的增加脚本小子构造请求的难度？

**Comment by thbourlove** [comment]
主要用于保证用户拿到的server seed hash一定是从我们这里给出去的，否则会导致用户转了账但是无法帮他开奖的情况。

**Comment by onigirisan** [comment]
另外可以避免为了防止hash重放攻击而保存hash全表浪费内存

**Comment by littlekfc** [comment]
另外再问一下，那个随机种子为啥要去掉时间和相关的链上信息？加上不是更鲁棒吗？

**Comment by thbourlove** [comment]
加上后，开发者可以通过控制链上信息和开奖时间来控制最后的开奖结果。所以除了client seed 和 server seed之外，最后开奖时生成的随机数不应该依赖其他信息。

**Comment by foonsun** [comment]
@onigirisan transfer 方法最后发送了receipt 方法，但是receipt方法中只有一行代码，那最后是怎么引发最后的开奖方法的?谢谢
