### ISSUE TITLE
Why are only 3 expired hashes deleted?

### ISSUE THREAD

**Issue by MrToph** [Dappub/fairdicegame#7]
Hi,
any reason why only 3 expired hashes are deleted here?

https://github.com/Dappub/fairdicegame/blob/360fc5b02a48bb6de047389dfe472db7b266e9cb/fairdicegame/include/fairdicegame.hpp#L127

Edit: I guess it's to circumvent the maximum transaction time? Otherwise, it could lead to the contract permanently being stuck.

**Comment by thbourlove** [comment]
you are right, just to circumvent the maximum transaction time.
